- platform: generic
  name: Vacuum Map
  still_image_url: http://localhost:10005/map.png
  framerate: 1

- platform: generic
  name: Vacuum Grid Map
  still_image_url: http://localhost:10005/map.grid.png
  framerate: 1

- platform: ffmpeg
  input: https://hoktastream1.webcamera.pl/wentzl_cam_be5c6c/wentzl_cam_be5c6c.stream/playlist.m3u8
  name: Main Square

- platform: ffmpeg
  input: https://hoktastream2.webcamera.pl/krakow_cam_4c3e37/krakow_cam_4c3e37.stream/chunks.m3u8
  name: Wawel 

- platform: mjpeg
  mjpeg_url: !env_var HOME_ASSISTANT_HIM_CAM_URL
  username: pi
  password: !env_var HOME_ASSISTANT_HIM_CAM_PASSWORD
  name: him_cam


- platform: mjpeg
  mjpeg_url: http://192.168.1.237:2971/camera/stream
  name: Nexus 7
