
# Nginx
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/speedtest.conf
      template:
        src: speedtest.conf.j2
        dest: /etc/nginx/sites-enabled/speedtest.conf
      notify:
        - reload nginx
        - restart nginx