- hosts: master
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    ufw_reset: no
    ufw_logging: "off"
    ufw_rules:
      - { port: 53, rule: allow, comment: 'Allow PiHole DNS' }
      - { port: 68, rule: allow, comment: 'Allow PiHole DNS' }
      - { port: 853, rule: allow, comment: 'Allow PiHole DNS' }
      - { port: 67, rule: allow, comment: 'Allow PiHole DNS' }

- hosts: master
  become: yes
  roles:
    - role: geerlingguy.certbot
  vars:
    certbot_auto_renew: false
    certbot_admin_email: "{{ email }}"
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
        - "{{ adguard_domain }}"

# Nginx
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/ads.conf
      template:
        src: ads.conf.j2
        dest: /etc/nginx/sites-enabled/ads.conf
      notify:
        - reload nginx
        - restart nginx