- hosts: master
  become: yes
  roles:
    - role: geerlingguy.certbot
  vars:
    certbot_auto_renew: false
    certbot_admin_email: "{{ email }}"
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
        - "notes.{{ domain }}"

# Nginx
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/notes.conf
      template:
        src: notes.conf.j2
        dest: /etc/nginx/sites-enabled/notes.conf
      notify:
        - reload nginx
        - restart nginx