

- platform: mqtt
  state_topic: "poland/beer_flu/zakazenia"
  name: beer_flu_current
  unit_of_measurement: people

- platform: mqtt
  state_topic: "poland/beer_flu/hospitalizacja"
  name: beer_flu_hospital
  unit_of_measurement: people

- platform: mqtt
  state_topic: "poland/beer_flu/zgony"
  name: beer_flu_deaths
  unit_of_measurement: people

- platform: mqtt
  state_topic: "poland/beer_flu/testy"
  name: beer_flu_tests
  unit_of_measurement: people


