- platform: template
  sensors:
    power_consumption:
      friendly_name: "Power consumption"
      unit_of_measurement: 'W'
      value_template: >- 
        {{ float(states.sensor.fibaro_system_fgs213_switch_power.state) +
            float(states.sensor.fibaro_system_fgs213_switch_power_2.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_3.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_4.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_5.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_7.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_8.state)+
            float(states.sensor.fibaro_system_fgs213_switch_power_9.state)+
            float(states.sensor.fibaro_system_fgs223_double_relay_power.state)+
            float(states.sensor.fibaro_system_fgs223_double_relay_power.state)+
            float(states.sensor.living_room_humidifier_current.state)+
            float(states.sensor.router_power_status.state)+
            float(states.sensor.cover_power.state)
        }}
