- platform: public_transit
  name: back_from_work_transit
  from: "Białucha"
  to: "Wzgórza Krzesławickie"
  count: 5
  endpoint: "http://localhost:5000/api"

- platform: public_transit
  name: to_work_transit
  from: "Wzgórza Krzesławickie"
  to: "Nowy Bieżanów P+R"
  count: 3
  endpoint: "http://localhost:5000/api"